name: Build static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the PAT_TOKEN to allow deployment to Pages
permissions:
    contents: write
    pages: write
    id-token: write
  
# Allow one concurrent deployment
# concurrency:
#     group: "pages"
#     cancel-in-progress: true


env:
  node-version: '20.14.0'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout main
          uses: actions/checkout@v4
          with:
            token: ${{ secrets.PAT_TOKEN }}
            fetch-depth: 0
            ref: main

        - name: Set up git
          run: |
            git config --global user.email "you@example.com"
            git config --global user.name "maxksorg builder"

        - name: "Merge changes from main to pages"
          run: |
            git fetch origin
            git checkout pages
            git merge --strategy-option theirs main

        - name: "Get last update of files"
          run: |
            git ls-tree -r --name-only HEAD | while read filename; do
              unixtime=$(git log -1 --format="%at" -- "${filename}")
              touchtime=$(date -d @$unixtime +'%Y%m%d%H%M.%S')
              touch -t ${touchtime} "${filename}"
            done

        - name: "Clean up public/"
          run: |
            rm -rf public/

        - name: Use Node.js ${{ env.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ env.node-version }}

        - name: "Install webapp"
          run: |
            npm install
  
        - name: "Build webapp"
          run: |
            npm run build

        - name: "Push new build to pages"
          run: |
            git add .
            currentDate="`date +'%Y-%m-%d %H:%M:%S'`"
            gitmsg="Build: $currentDate"
            git commit -m "$gitmsg"
            git push -u origin pages --force